# Generated by Django 3.1.5 on 2022-02-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('content', models.TextField()),
                ('link', models.URLField(blank=True, null=True)),
                ('date', models.DateField(blank=True)),
                ('is_open', models.BooleanField(default=False)),
            ],
        ),
    ]
