# Generated by Django 3.1.5 on 2022-02-05 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='broadcast',
        ),
    ]
