# Generated by Django 3.0.3 on 2021-03-04 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
    ]
