# Generated by Django 3.1.5 on 2022-02-05 15:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_news_broadcast'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='broadcast',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
