# Generated by Django 3.1.5 on 2021-03-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='type',
            field=models.IntegerField(choices=[(0, 'Development Boards'), (1, 'Sensors and Electronic Components'), (2, 'Motors and Motor Drivers'), (3, 'Tools'), (4, 'Power and Battery '), (5, 'Transmitter and Receiver'), (6, 'Miscellaneous')], default=6),
        ),
    ]
