# Generated by Django 3.1.5 on 2021-02-16 16:27

import component.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0002_auto_20210213_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='image',
            field=models.ImageField(default='default-component.png', upload_to=component.models.get_path),
        ),
    ]
