# Generated by Django 3.0.3 on 2021-03-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0003_auto_20210313_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='time_confirmation',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
