# Generated by Django 3.0.3 on 2021-02-06 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0004_auto_20210202_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='detail',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='issued_num',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='component',
            name='type',
            field=models.IntegerField(choices=[(0, 'Batteries and Chargers'), (1, 'Development Boards'), (2, 'Drivers'), (3, 'Electronic Tools'), (4, 'Mechanical Tools'), (5, 'Robotics KIT'), (6, 'Sensors'), (7, 'Others')], default=0),
        ),
        migrations.AlterField(
            model_name='request',
            name='reason',
            field=models.TextField(blank=True, default='', max_length=128, null=True),
        ),
    ]
