# Generated by Django 3.0.3 on 2021-02-06 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0005_auto_20210206_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='time_confirmation',
            field=models.TimeField(default=None),
        ),
    ]
