# Generated by Django 3.0.3 on 2021-02-06 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0007_remove_request_time_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='time_confirmation',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
