# Generated by Django 3.1.5 on 2021-02-16 16:21

import component.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0008_request_time_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='image',
            field=models.ImageField(default='default-comp.png', upload_to=component.models.user_directory_path),
        ),
    ]
