# Generated by Django 3.1.5 on 2021-02-05 18:41

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('blog', '0002_auto_20210126_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='imagelink',
            field=models.URLField(default="{% static 'img/r9.jpg'%}"),
        ),
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
