# Generated by Django 3.1.5 on 2021-03-10 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210308_1930'),
        ('blog', '0002_auto_20210309_0822'),
    ]

    operations = [
    ]
