# Generated by Django 3.0.3 on 2021-02-06 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210205_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='imagelink',
            field=models.URLField(),
        ),
    ]
