# Generated by Django 3.0.3 on 2021-02-06 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210206_1029'),
        ('blog', '0003_blog_approved'),
    ]

    operations = [
    ]
