# Generated by Django 3.1.5 on 2021-02-10 10:09

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210208_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='default-blog.png', upload_to=blog.models.user_directory_path),
        ),
    ]
