# Generated by Django 3.0.3 on 2021-02-11 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210210_0004'),
        ('blog', '0007_auto_20210210_1539'),
    ]

    operations = [
    ]
