# Generated by Django 3.0.3 on 2021-01-14 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('github', models.URLField(blank=True)),
                ('vidlink', models.URLField(blank=True)),
                ('detail', models.TextField()),
                ('status', models.IntegerField(choices=[(0, 'Ongoing'), (1, 'Completed'), (2, 'Abandoned')], default=0)),
            ],
        ),
    ]
