# Generated by Django 3.1.5 on 2021-02-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='comp_and_tech',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
