# Generated by Django 3.0.3 on 2021-03-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20210217_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='overview',
            field=models.TextField(blank=True),
        ),
    ]
