# Generated by Django 3.1.5 on 2021-02-10 10:09

from django.db import migrations, models
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default='default-project.png', upload_to=project.models.user_directory_path),
        ),
    ]
