# Generated by Django 3.0.3 on 2021-03-11 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_sharekey_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharekey',
            name='project',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sharelink', to='project.Project'),
        ),
    ]
