# Generated by Django 3.1.5 on 2021-03-13 17:01

from django.db import migrations, models
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20210311_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, upload_to=project.models.get_path),
        ),
    ]
