# Generated by Django 3.1.5 on 2021-02-12 19:41

from django.db import migrations, models
import workshop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('date', models.DateField()),
                ('venue', models.CharField(blank=True, max_length=256)),
                ('link', models.FileField(blank=True, null=True, upload_to=workshop.models.get_path)),
                ('image', models.ImageField(default='default-workshop.png', upload_to=workshop.models.get_path)),
                ('date_posted', models.DateField()),
                ('status', models.IntegerField(choices=[(0, 'Past'), (1, 'Upcoming')], default=1)),
            ],
        ),
    ]
