# Generated by Django 3.0.3 on 2021-02-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='target',
            field=models.CharField(default='All', max_length=256),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='venue',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
