# Generated by Django 3.1.5 on 2021-03-13 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0003_workshop_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
