# Generated by Django 3.1.5 on 2021-02-12 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(blank=True, max_length=256)),
                ('regnum', models.IntegerField(blank=True)),
                ('branch', models.IntegerField(blank=True, choices=[(0, 'Biotechnology Engineering'), (1, 'Civil Engineering'), (2, 'Electrical Engineering'), (3, 'Mechanical Engineering'), (4, 'Computer Science Engineering'), (5, 'Electronics and Communication Engineering'), (6, 'Production and Industrial Engineering'), (8, 'Information Technology'), (9, 'Chemical Engineering')])),
                ('role', models.IntegerField(choices=[(0, 'Temporary Ban'), (1, 'Member'), (2, 'Coordinator'), (3, 'Head')], default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
