# Generated by Django 4.2.1 on 2023-07-05 13:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(blank=True, max_length=256)),
                ('regnum', models.IntegerField(blank=True, null=True, unique=True)),
                ('branch', models.IntegerField(blank=True, choices=[(0, 'Biotechnology'), (1, 'Civil Engineering'), (2, 'Electrical Engineering'), (3, 'Mechanical Engineering'), (4, 'Computer Science and Engineering'), (5, 'Electronics and Communication Engineering'), (6, 'Production and Industrial Engineering'), (8, 'Information Technology'), (9, 'Chemical Engineering')], null=True)),
                ('role', models.IntegerField(choices=[(0, 'Temporary Ban'), (1, 'Member'), (2, 'Coordinator'), (3, 'Head')], default=1)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('phone', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
