# Generated by Django 3.0.3 on 2021-02-04 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='rank',
            new_name='role',
        ),
    ]
