# Generated by Django 3.1.5 on 2021-02-12 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='regnum',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
