# Generated by Django 3.1.5 on 2021-03-12 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210310_1230'),
        ('user', '0002_auto_20210310_1324'),
    ]

    operations = [
    ]
