# Generated by Django 3.0.3 on 2021-02-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210213_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='branch',
            field=models.IntegerField(blank=True, choices=[(0, 'Biotechnology'), (1, 'Civil Engineering'), (2, 'Electrical Engineering'), (3, 'Mechanical Engineering'), (4, 'Computer Science & Engineering'), (5, 'Electronics and Communication Engineering'), (6, 'Production and Industrial Engineering'), (8, 'Information Technology'), (9, 'Chemical Engineering')], default=5, null=True),
        ),
    ]
